### ISSUE TITLE
1.1.0 版本计划

### ISSUE THREAD

**Issue by Sayi** [Sayi/swagger-dubbo#1]
* object参数的string json格式可视化
* 重载方法http调用优化

**Comment by chengcheng768** [comment]
你这种方法,我的理解是不是,前端http请求过来,然后直接打到后端的dubbo服务接口上呢

**Comment by Sayi** [comment]
@chengcheng768  目前来说是这样的，映射到单机服务接口，没有再通过RPC调用dubbo服务。
