### ISSUE TITLE
通过注解方式暴露dubbox的服务，生成swagger文档报异常

### ISSUE THREAD

**Issue by philhong2012** [Sayi/swagger-dubbo#2]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
 org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
 org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
 org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 </pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
 com.deepoove.swagger.dubbo.config.DubboPropertyConfig.configure(DubboPropertyConfig.java:43)
 com.deepoove.swagger.dubbo.web.SwaggerDubboController.getApiList(SwaggerDubboController.java:61)
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
 org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
 org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
 org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
 org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
 org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
 org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
 org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
 org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
 org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by Sayi** [comment]
没有在dubbox上验证过，我晚些时候看下。

**Comment by Sayi** [comment]
dubbo2.6.0+对注解方式修复了很多bug，swagger-dubbo不准备支持旧版本的注解
