### ISSUE TITLE
为何是ServiceBean而不是ReferenceBean

### ISSUE THREAD

**Issue by andarly** [Sayi/swagger-dubbo#3]
扫描ServiceBean，类似于单体应用，没有实际模拟rpc场景。
建议扫描ReferenceBean，这样才能模拟rpc吧。

**Comment by Sayi** [comment]
现在的确是单机验证场景。

首先生产环境是不适合使用swagger-dubbo的。

基于以下目的，测试环境实现的是单机场景:
1. 文档化，不区分单机和RPC
2. 测试和验证接口的功能性，接口测试，也不区分单机和RPC
3. 模拟调用：因为测试环境相同服务部署在多台机器的情况下，如果没有明确服务版本号限制，可能会导致接口的执行结果不一致

谢谢建议，我考虑可以加个配置，单机或者RPC，如果是RPC，则进行RPC调用。

**Comment by Sayi** [comment]
现在的版本已经默认支持RPC调用
