### ISSUE TITLE
关于dubbo的provider设置了group和version的问题

### ISSUE THREAD

**Issue by 85825600** [Sayi/swagger-dubbo#30]
如果dubbo的provider设置了group和version，调试时报错
Failed to check the status of the service com.linlong.tp.dubbo.IDemoService. No provider available for the service com.linlong.tp.dubbo.IDemoService from the url zookeeper://172.27.55.10:2181/com.alibaba.dubbo.registry.RegistryService?application=cll-tp-channel-service&dubbo=2.6.2&interface=com.linlong.tp.dubbo.IDemoService&methods=getDemoList,getDemoList2,getDemoList1&pid=11248&register.ip=192.168.4.128&revision=1.0.0-SNAPSHOT&side=consumer&timestamp=1536930259366 to the consumer 192.168.4.128 use dubbo version 2.6.2

**Comment by 15168326318** [comment]
dubbo的provider设置了group和version的问题有解决吗 ？我们测试员发现这个问题了，等着测试呢 ？
