### ISSUE TITLE
问一下，你这个项目要怎么才能测试我们自己开发的接口，你们的demo是可以的。你文档写的太简单了，我都不知道怎么用来测试我们的接口。

### ISSUE THREAD

**Issue by 15168326318** [Sayi/swagger-dubbo#33]

**Comment by 15168326318** [comment]
<dependency>
			<groupId>cc.ewell.dubbo</groupId>
			<artifactId>api</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>  这样引入后，ui页面什么都没有，我注册中心都连上了也有服务在里面了呀 ？

**Comment by Sayi** [comment]
无效issue
