### ISSUE TITLE
你这个项目感觉对要测试的业务项目侵入太大，要加入你们的静态页面还要改成web项目。我们dubbo本来就是非web项目，用来提供服务的。

### ISSUE THREAD

**Issue by 15168326318** [Sayi/swagger-dubbo#34]

**Comment by 15168326318** [comment]
能不能只要提供要测试api接口包，测试的时候直接调用注册中心的服务。
    这样对我的业务项目就没有侵入了，这样才完美。

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/47891863-ec3e5e00-de8f-11e8-9035-bacfac30f6df.png)
