### ISSUE TITLE
现在支持dubbo的provider设置group和version的功能吗？

### ISSUE THREAD

**Issue by 15168326318** [Sayi/swagger-dubbo#35]

**Comment by 15168326318** [comment]
java.lang.IllegalStateException: Failed to check the status of the service com.example.service.UserService. No provider available for the service com.example.service.UserService from the url zookeeper://192.168.198.94:32176/com.alibaba.dubbo.registry.RegistryService?application=dubbo-custom&dubbo=2.0.2&interface=com.example.service.UserService&methods=getUser,getUserName&pid=30332&register.ip=192.168.110.34&side=consumer&timestamp=1544522666605 to the consumer 192.168.110.34 use dubbo version 2.6.3
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:422) ~[dubbo-2.6.3.jar:2.6.3]


这是报错信息？

**Comment by lijiaoshou** [comment]
一样的问题，昨天调试了源码，目前2.0.1版本确实不支持增加group的设置，但是感觉仅仅是swagger-dubbo包修改也不行，dubbo包也要相应的修改，加入group信息。
作者后续有增加group设置支持的打算吗？

**Comment by Sayi** [comment]
最近一段日子没有时间维护这个项目，原有的设计有点繁杂，2019年打算彻底重构下。

**Comment by 15168326318** [comment]
我也要自己改代码了，现场测试部门都催我解决这个问题。
@lijiaoshou 你这样还是有个问题，在application里配置的版本号这样是取不到的。还需要重环境变量里去取。
