### ISSUE TITLE
在dubbox 2.8.4版本上获取不到service

### ISSUE THREAD

**Issue by Power-Snow** [Sayi/swagger-dubbo#37]
在dubbo2.6.0没有问题，然后换成dubbox2.8.4 ，其他不变，/swagger-dubbo/api-docs  这个接口拿不到数据

**Comment by lichenhui1234** [comment]
我也遇到了相同的问题,请问你们是怎么解决的呢

**Comment by jingui123** [comment]
同样，最后怎么解决的呢，我看这个必须要加@DubboComponentScan,但我们用2.7.7并没有这个注解
