### ISSUE TITLE
dubbo 2.7+ 获取不到服务

### ISSUE THREAD

**Issue by ForChangeNero** [Sayi/swagger-dubbo#49]
swagger-dubbo/api-docs
只返回
{
"swagger": "2.0",
"basePath": "/tradecenter"
}

**Comment by KevinClair** [comment]
同问，大佬问题解决了吗？

> swagger-dubbo/api-docs
> 只返回
> {
> "swagger": "2.0",
> "basePath": "/tradecenter"
> }
