### ISSUE TITLE
dubbo2.6.5不能获取到ServletContext

### ISSUE THREAD

**Issue by Ryan-Miao** [Sayi/swagger-dubbo#52]
启动报错， 错误和版本如下

Field servletContext in com.deepoove.swagger.dubbo.config.DubboPropertyConfig required a bean of type 'javax.servlet.ServletContext' that could not be found.

```
com.deepoove:swagger-dubbo:jar:2.0.1:compile,  
com.alibaba.boot:dubbo-spring-boot-starter:jar:0.1.2.RELEASE:compile,
com.alibaba:dubbo:jar:2.6.5:compile
```

**Comment by jinkai125** [comment]
嗨喽，我们遇到了同样的问题。这个可以描述下是怎么解决的吗？

**Comment by xwx2015** [comment]
dubbo 2.7.7也遇到这个问题了，请问怎么解决的

**Comment by xwx2015** [comment]
> 嗨喽，我们遇到了同样的问题。这个可以描述下是怎么解决的吗？

老哥后来解决了吗
