### ISSUE TITLE
使用内嵌的jetty容器会导致访问dubbo接口404

### ISSUE THREAD

**Issue by zhaojigang** [Sayi/swagger-dubbo#8]
![image](https://user-images.githubusercontent.com/14085645/37344998-dc99935c-2706-11e8-9045-dbf816c05cc8.png)
您遇到过这个问题吗？
![image](https://user-images.githubusercontent.com/14085645/37345131-3007469c-2707-11e8-8517-bead92131210.png)

**Comment by Sayi** [comment]
和jetty容器应该没关系，服务是基于SpringMVC暴露出去的。

可以看看启动日志？是不是路径映射(url mapping)有问题？

**Comment by zhaojigang** [comment]
ok，问题解决了，谢谢
