### ISSUE TITLE
请问为啥我访问那个地址http://localhost:8080/XXX/swagger-dubbo/swagger.json，显示的是json，而不是页面

### ISSUE THREAD

**Issue by renxz** [Sayi/swagger-dubbo#9]

**Comment by Sayi** [comment]
swagger-ui是个单独的项目，需要自己集成的。
参见官方文档：[https://github.com/swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by renxz** [comment]
谢谢
